### ISSUE TITLE
Stream encoding - when to decode

### ISSUE THREAD

**Issue by Ploppz** [pdf-rs/pdf#10]
In most cases, a stream ought to be decoded in order to be used by the PDF library (or an a (for example an xref stream). As it is right now, this is done during parsing (`parser/mod.rs`). In other cases, the encoded data doesn't need to be encoded before it is consumed by the application. Example: DCT filter for JPEG stream.
Need a policy for when to keep it as it is, and when to decode.
Simplest idea, and **what I will do now**:
- Don't decode in `parser/mod.rs`.
- The derivation will assume that the `info` field has a `filter` field ... all streams have this anyway.
- In the derivation of stream-based Objects, add option whether or not to decode the stream in `from_primitive()`.
Hence, it's up to each Object, whether or not they need the encoded or decoded data. I'm not sure whether this is the best way yet. ((Another idea is to just decode in `parser/mod.rs` depending on what filters are on it (e.g. _not_ in the case of DCT filter). It would still require that data about _which filters are still encoded on the data_.))

**Comment by s3bk** [comment]
This is solved in #25 which lazily decodes the stream on the first call to `Stream::data()`

**Comment by s3bk** [comment]
With #25 steams are decoded when first needed. This introduces minimal overhead and internal mutability, but avoids unnecessary work.
