### ISSUE TITLE
Type3 fonts cannot be loaded

### ISSUE THREAD

**Issue by tarfu** [pdf-rs/pdf#108]
Hello,

First, thanks for all the effort with this library.

I came across the issue that Type3 fonts cannot be loaded as these don't have a field `BaseFont`. `BaseFont` on the other hand is required in the library as it is required for numerous other types of fonts. https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/pdf_reference_archives/PDFReference.pdf Page 323

I want to ask if that is for a reason or an oversight. I would be able to provide a pull request, but we should decide on a fix, as just making `BaseFont` optional has other implications, I think.

Thanks

**Comment by s3bk** [comment]
It looks like `BaseFont` is only used for the name. You can make that optional.

**Comment by tarfu** [comment]
When implementing the change and using it a bit, it is quite cumbersome to use if it is not a type3 font.
Maybe not making name optional but setting a dummy would be nicer from a non type3 perspective, but not really correct either.
