### ISSUE TITLE
PageTree.count = 0 when it should be 1

### ISSUE THREAD

**Issue by Ploppz** [pdf-rs/pdf#11]
@compenguy has the following problem

https://github.com/compenguy/pdftext (run `cargo test`): document has 1 page, but the `pdf` lib says it has 0, because the `PageTree` has count = 0.

[inspect-prim](https://github.com/pdf-rs/inspect-prim) shows that the `/Count` value of the page tree is in fact `1`. (just run `cargo run`)

I will look take a look again later.

**Comment by s3bk** [comment]
Has been fixed: https://github.com/s3bk/pdftext

**Comment by Ploppz** [comment]
Nice! @compenguy
