### ISSUE TITLE
Panic in `crypt.rs` when slicing into key

### ISSUE THREAD

**Issue by 5225225** [pdf-rs/pdf#126]
`thread '<unnamed>' panicked at 'range end index 32 out of range for slice of length 25', /home/jess/src/pdf/pdf/src/crypt.rs:572:17`

[crash.pdf](https://github.com/pdf-rs/pdf/files/7836225/crash.pdf)

https://github.com/pdf-rs/pdf/blob/dc3016b8d90ffea3bba2f86843274b7438c7092a/pdf/src/crypt.rs#L569-L575

**Comment by s3bk** [comment]
Is that supposed to decrypt correctly?

**Comment by s3bk** [comment]
I see a preview in dolphin, but okular wants a password..

**Comment by 5225225** [comment]
It was fuzzed, I just threw in all the files from the tests folder. So it's probably too corrupted to *have* a valid password.

Still, shouldn't panic.

**Comment by s3bk** [comment]
okay, then it should be fixed.
