### ISSUE TITLE
Non working PDF

### ISSUE THREAD

**Issue by Kaporos** [pdf-rs/pdf#127]
Hey guys ! 
I just tried to run your example on a pdf on my own (actually my project is to automatically read my report card points from my school platform and send my a notification when there's new ones)

So, i tried to run:

cargo run --example read -- files/bulletin.pdf
cargo run --example text -- files/bulletin.pdf

But there was not any output (the mistake might be from my side, idk)

If the problem comes from your lib, here's the pdf, just in case you wanna investigate on it (I'm not saying "Please fix it" because i know how hard it is to work on an open source project)

Have a nice day !

[report.pdf](https://github.com/pdf-rs/pdf/files/8053511/report.pdf)

**Comment by s3bk** [comment]
Hello,

if you want to extract text, there I highly suggest to use https://github.com/pdf-rs/pdf_render/blob/master/render/examples/trace.rs for now.

Unfortunately text extraction is very difficult and I decided that it is outside the scope of this repository.

**Comment by s3bk** [comment]
I can confirm, no output.

**Comment by s3bk** [comment]
Those are images!
