### ISSUE TITLE
impl Backend for Mmap is unsound

### ISSUE THREAD

**Issue by nox** [pdf-rs/pdf#13]
You can't just call `Mmap` methods behind `unsafe` code and call it a day. If someone modifies the file, even from another program, things will go very badly. One should be able to read a PDF document from an `Mmap` value only from unsafe code.

I would suggest killing `Backend::open` and let people initialise their `MMap` or `Vec<u8>` inputs themselves.

**Comment by Ploppz** [comment]
Thanks for noticing. I did what you suggested.
