### ISSUE TITLE
`Can't parse field root of struct RcRef < Catalog >.` when trying to read pdf content

### ISSUE THREAD

**Issue by qarmin** [pdf-rs/pdf#133]
Code used to find problem
```
            let result = panic::catch_unwind(|| {
                if let Err(e) = pdf::file::File::open(&path) {
                    let error = unpack_error(e);
                    match error {
                        InvalidPassword => {
                            return;
                        }
                        _ => {}
                    }
                    println!("{}    -     {}", path, error);
                } else {
                    // println!("VALID   {}", path);
                }
            });
```
I have more such broken files, most of them are downloaded from internet, but not all
[norbertocarlos_vim.bw.pdf](https://github.com/pdf-rs/pdf/files/8693778/norbertocarlos_vim.bw.pdf)

PDF validator doesn't show anything really bad with this PDF - https://tools.pdfforge.org/validate-pdfa

**Comment by s3bk** [comment]
```
46 0 obj
<<
/__WKANCHOR_2 18 0 R
/__WKANCHOR_o 38 0 R
/__WKANCHOR_4 19 0 R
/__WKANCHOR_q 39 0 R
/__WKANCHOR_6 20 0 R
/__WKANCHOR_a 21 0 R
/__WKANCHOR_8 22 0 R
/__WKANCHOR_c 23 0 R
/__WKANCHOR_e 24 0 R
/__WKANCHOR_g 25 0 R
/__WKANCHOR_i 26 0 R
/__WKANCHOR_k 27 0 R
/__WKANCHOR_m 40 0 R
>>
50 0 obj
```
So it is missing the `endobj` after the dict ends.

I can add a flag to ignore this.

**Comment by s3bk** [comment]
It should be fixed.
use a File::*_with_options method to set the ParseOptions to tolerant

**Comment by qarmin** [comment]
Not sure why, but looks that enabling `allow_error_in_option` fixes problem instead `allow_missing_endobj`.
In commit I don't see any strange things, that could do this.
