### ISSUE TITLE
New version and dependencies update

### ISSUE THREAD

**Issue by qarmin** [pdf-rs/pdf#135]
Last version was released more than 1 year ago and since this time I see that library was greatly improved but I can't use them due needing to use only versions released in crates.io

Also looks that some external dependencies are outdated which cause a little bloat in my Cargo.lock file because now my project use 2 different versions of same crate. 
https://deps.rs/repo/github/pdf-rs/pdf/ - is a great site to show which dependencies are outdated

**Comment by s3bk** [comment]
Good reminder.

I need to figure out what changed in `aes` and how to deal with the pending PR in `datasize`, but apart from that, things are not looking too bad.
