### ISSUE TITLE
Add an example that extracts all texts from a PDF

### ISSUE THREAD

**Issue by SirVer** [pdf-rs/pdf#14]
I am looking for an alternative to `pdftotext`, such an example would be tremendously useful also as a quick start.

**Comment by jrmuizel** [comment]
https://github.com/jrmuizel/pdf-extract/blob/master/examples/extract.rs is an example that does text extraction like pdftotext using lopdf instead of pdf-rs.

**Comment by SirVer** [comment]
@jrmuizel Thanks, so far that seems to be the best tool for the job. However I still think an example for pdf-rs to that effect would be very welcome.

**Comment by s3bk** [comment]
@SirVer: I quickly wrote [an example](https://github.com/pdf-rs/pdf/blob/master/examples/text.rs) that does about that:  . However it would need some whitespace detection in order to be really usable.

**Comment by SirVer** [comment]
Thanks!
