### ISSUE TITLE
UnexpectedPrimitive { expected: "Reference", found: "Dictionary" }

### ISSUE THREAD

**Issue by MrMarnic** [pdf-rs/pdf#151]
I am trying to get images out of my pdf. I am using the code from the examples.

```
images.extend(res.xobjects.iter().map(|(_name, &r)| file.get(r).unwrap())
        .filter(|o| matches!(**o, XObject::Image(_)))
    );
```
But I get this error:
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Shared { source: Try { file: "C:\\Users\\Marcel\\.cargo\\git\\checkouts\\pdf-3ef1c528a9b91eec\\9aacaae\\pdf\\src\\content.rs", line: 537, column: 22, context: Context([]), source: FromPrimitive { typ: "Option < MaybeRef < Resources > >", field: "resources", source: FromPrimitive { typ: "HashMap < Name, Ref < Font > >", field: "fonts", source: UnexpectedPrimitive { expected: "Reference", found: "Dictionary" } } } } }`

**Comment by s3bk** [comment]
Please verify, but this exact error should be gone.

**Comment by s3bk** [comment]
I had to adjust the example slightly
