### ISSUE TITLE
Publish `pdf` 0.8.0 to crates.io?

### ISSUE THREAD

**Issue by Billy-Sheppard** [pdf-rs/pdf#155]
Is there a reason the current master branch isn't published? 0.7.2 doesn't compile for me due to unsendable futures, but the master branch is fine.

Is there bugfixing required?

**Comment by s3bk** [comment]
Yes, the master branch is far ahead from the last published version.
I am currently blocked on https://github.com/CasperLabs/datasize-rs/pull/7

**Comment by Billy-Sheppard** [comment]
Hi @marc-casperlabs, apologies for the ping, would you be able to provide a datasize-rs version update and publish?

I believe thats all @s3bk needs to push forward on a pdf 0.8 release?

Thanks

**Comment by marc-casperlabs** [comment]
It's on my list - sadly, I got sick before Christmas break, before I could tackle this. I'll do my best to get this published before year's end.

**Comment by marc-casperlabs** [comment]
`0.2.13` has been published to crates.io, see please check if this addresses your issues. Happy Holidays!

**Comment by s3bk** [comment]
Thank you very much!

**Comment by s3bk** [comment]
Version 0.8.0 has been released

**Comment by Billy-Sheppard** [comment]
Thanks to both of you for your work over the holidays <3
