### ISSUE TITLE
encrypted pdf (1.4) panics

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [pdf-rs/pdf#157]
When i try to load a PDF (version 1.4)  that uses encryption, I get this error:

```
thread 'main' panicked at 'range end index 128 out of range for slice of length 16', <home>/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/9ab086c/pdf/src/crypt.rs:258:43
```

I am using pdf this way in may Cargo.toml:

```
https://github.com/pdf-rs/pdf.git
```

Looking at crypt.rs, it makes sense.

The error occurs int his line: https://github.com/pdf-rs/pdf/blob/master/pdf/src/crypt.rs#L258
The index is taken in `data`, which is the result of

```
let mut data = *hash.compute();
```

and has a fixed length of 16, but the keysize is 128.

**Comment by RudolfVonKrugstein** [comment]
I would like to contribute, but I am unsure how the correct decryption should work.
Do you have a specification you followed when implementing the crypt part?

**Comment by s3bk** [comment]
The only specification is the [PDF3200](https://opensource.adobe.com/dc-acrobat-sdk-docs/standards/pdfstandards/pdf/PDF32000_2008.pdf) specification.

**Comment by s3bk** [comment]
I think 128 is the length in bits, as it is 16 bytes. So somewhere there is a /8 missing
