### ISSUE TITLE
Loading PDF gets stuck at `READ XREF AND TABLE`

### ISSUE THREAD

**Issue by hahnrobert** [pdf-rs/pdf#18]
When loading [this PDF](http://www.europarl.europa.eu/sides/getDoc.do?pubRef=-//EP//NONSGML+COMPARL+PE-612.246+01+DOC+PDF+V0//EN&language=EN) via this code, the program gets stuck:
`let _file = pdf::file::File::<Vec<u8>>::open("test1.pdf")?;`

**Comment by Ploppz** [comment]
It seems if you try to run it a little longer, it outputs the error:
```
 === 
Error: Key Root: cannot convert from primitive to type Catalog
  caused by: Key StructTreeRoot: cannot convert from primitive to type Option < StructTreeRoot >
  caused by: Tried to dereference free object nr 133.
 === 
```
Looking at the Catalog type, StructTreeRoot is optional. Inspecting the pdf reveals that indeed there is a reference to a non-existent/free object. So I think the best fix is to treat such references as absence of the object rather than error. Working on it.

**Comment by Ploppz** [comment]
Done and pushed to master.
Interesting to note how slow it reads the object. Should definitely be benchmarked.
When running with `--release` it takes 6 seconds, and without it takes 154 seconds...

**Comment by Ploppz** [comment]
When I benchmarked it, seems like most of that time is spent in `error_chain`. I should definitely look into that. But I should also switch to using `failure`. Maybe that's somehow better.

**Comment by Ploppz** [comment]
@hahnrobert I don't know if you are still interested, but it seems that with the latest rewrite, reading is much faster. On current master, run `cargo run -p read -- files/ep.pdf`. (That file is the one you linked in this issue)

**Comment by s3bk** [comment]
there is also `--release` which should make it at least one magnitude faster
