### ISSUE TITLE
thread 'main' panicked at 'Unknown element: Number(4050.0)',

### ISSUE THREAD

**Issue by tokatoka** [pdf-rs/pdf#184]
```
toka@toka:~/repro$ ./target/release/repro crash-9c8.pdf 
thread 'main' panicked at 'Unknown element: Number(4050.0)', /home/toka/.cargo/git/checkouts/pdf-3ef1c528a9b91eec/a6e2abc/pdf/src/encoding.rs:63:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is the `main.rs` to reproduce
```rust
fn harness(file: &String) {
    if let Ok(file) = pdf::file::FileOptions::cached().open(file) {
        for idx in 0..file.num_pages() {
            let _ = file.get_page(idx);
        }
    }
}

fn main() {
    let args: Vec<String> = std::env::args().collect();

    let _ = harness(&args[1]);
}
```
and this is the crashing input
[crash-9c8.pdf](https://github.com/pdf-rs/pdf/files/11487116/crash-9c8.pdf)

https://github.com/pdf-rs/pdf/blob/a6e2abc96b23b64aa1051966bb000aabf1275d9f/pdf/src/encoding.rs#L63
This panic is triggered

**Comment by s3bk** [comment]
Are those files supposed to be correct?

**Comment by tokatoka** [comment]
> Are those files supposed to be correct?

No :grin: 
I edited fuzz/fuzz_targets and generated them. I opened a PR to update it to compile with the latest version
