### ISSUE TITLE
Error (unimplemented) trying to run the example with any of the files

### ISSUE THREAD

**Issue by Bogpan** [pdf-rs/pdf#190]
Trying to run the example with any of the example files gives the following error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Other { msg: "Unimplemented @ pdf\\src\\object\\stream.rs:151" }', pdf\examples\content.rs:37:27
```

Command used: `cargo run --example content -- files/example.pdf`. Saem happens for any of the other files. I know it's unimplemented but that's a bit weird, given that the example doesn't even work?

**Comment by s3bk** [comment]
I guess it is time to finally solve the file writing.
Thanks for reminding me.

**Comment by s3bk** [comment]
I did a bit of work and it does now run and produce a file that Okular can open.
