### ISSUE TITLE
Is it possible to "screenshot" a page?

### ISSUE THREAD

**Issue by artecoop** [pdf-rs/pdf#204]
Hello, and thanks for this library. I'm fairly new to rust and I've started with the super hard task of handling pdf.

What I need is to somehow "screenshot" all the pages of a pdf file and export them in bmp, for example, to perform some analysis.

I've also tried to get help from copilot, who suggest to use
`pdf::render::Context::new(resources.clone(), content.clone(), width, height);`

where resources and content come from the page I'm iterating in. But seems that Context::new does not exist anymore.

Any help or hint is very appreciated

**Comment by s3bk** [comment]
It is possible. Check out this example:
https://github.com/pdf-rs/pdf_render/tree/master/examples/pdf2image

It is possible that some pdfs will crash it with clip paths, if that happens let me know and I will try to add an option to disable them.

**Comment by s3bk** [comment]
It is only tested on linux. You may need to do some modifications for macos.
