### ISSUE TITLE
custom font supported?

### ISSUE THREAD

**Issue by Jing-Heng-Zhang** [pdf-rs/pdf#218]

**Comment by s3bk** [comment]
You need to  be a little more specific.

**Comment by Jing-Heng-Zhang** [comment]
thanks so much for your quick reply.
I have a project that needs to generate PDF file with Asian Fonts like Japanese,Chinese.
I want to know if it is possible to embed Font(like google fonts) to PDF file.
this  is the best PDF crate I've ever seen.
I appreaciate your great job.

**Comment by s3bk** [comment]
Of course. Embedding fonts is supported. But you will need to provide the font.

**Comment by Jing-Heng-Zhang** [comment]
Great!I will explore it

**Comment by s3bk** [comment]
https://github.com/pdf-rs/pdf/blob/master/pdf/examples/content.rs

Has a commented part that creates a font
