### ISSUE TITLE
Error when trying to load in a bytes from a database

### ISSUE THREAD

**Issue by hhamud** [pdf-rs/pdf#239]
I get this error

```shell
thread '<unnamed>' panicked at src/pdf.rs:35:49:
failed to load file in: Other { msg: "file header is missing" }
```

when trying to load in a file via Vec<u8> from a database
```rust
    let file = FileOptions::cached().load(data).expect("failed to load file in");
    debug!("file created");
```

**Comment by s3bk** [comment]
That sounds like a malformed PDF to me.
Can you try if other readers open the file?
If so, I can add an option to allow missing headers for you.

**Comment by hhamud** [comment]
> That sounds like a malformed PDF to me. Can you try if other readers open the file? If so, I can add an option to allow missing headers for you.

No worries it was a malformed pdf, (it was missing a few bytes).
