### ISSUE TITLE
Use of unstable features

### ISSUE THREAD

**Issue by divergentdave** [pdf-rs/pdf#28]
Is it on the roadmap to make `pdf` compatible with stable again? FYI, it looks like `#![feature(custom_attribute)]` is unused. Here's how the other unstable features are currently being used.

* `termination_trait_lib`: This is used in PdfError, to print error information while the process status code for the error is being fetched. This could be replaced with some boilerplate at each relevant `main()` function, to print out the same error information if an error bubbles all the way up.
* `try_trait`: This is used to implement a conversion from NoneError to PdfError. This conversion is only used once, in font.rs, and it could be replaced with `.ok_or(PdfError::Other { msg: ... }`.
* `core_intrinsics`: This is used to implement AnyObject and for error handling. I'm not familiar with this, but it's possible `std::any::Any` or the `typename` crates could fill in the gap here.

**Comment by s3bk** [comment]
- core_intrinsics:  can be removed if we add a `fn type_name(&self) -> &'static str` to `Object`
- try_trait: could be replaced with a try_opt! macro also adding location information at the same time (done)
- termination has just been removed.

**Comment by s3bk** [comment]
fixed core_intrinsics as well.
