### ISSUE TITLE
dump_data() issues

### ISSUE THREAD

**Issue by divergentdave** [pdf-rs/pdf#29]
I tried parsing a corrupt PDF file, and the program panicked with the following error. The unwrap() was in dump_data().

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: NotFound, error: PathError { path: "/tmp/pdf/oTRQva", err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', src/libcore/result.rs:999:5
```

After I created a `/tmp/pdf` directory, the panic went away. However, since I didn't have logging on, it created a file in `/tmp/pdf` without notifying me of its presence. I'd recommend two changes to this function:

* Instead of specifying a subdirectory, use the OS's default directory, and provide a file name prefix like `pdf-`
* Only write files out when an environment variable is set, and log a message with instructions on setting the environment variable to dump the buffer if the environment variable is not set

**Comment by s3bk** [comment]
it will now only write if you set PDF_OUT to a directory.

**Comment by divergentdave** [comment]
Sounds good, thanks!
