### ISSUE TITLE
Text extraction

### ISSUE THREAD

**Issue by s3bk** [pdf-rs/pdf#35]
Current status: works sometimes.

TODO:
 - needs to work reliable
 - attempt to extract blocks of text

**Comment by dougalg** [comment]
I am not able to get the same "text" script to work with any of the provided sample PDFs, nor my own PDFs.

**Comment by s3bk** [comment]
I can confirm, it is broken. I am probably going to remove it soon.

There are two alternatives:
- You can use pdf_render: `Cache::render_page` returns a `TraceResults` which contains the text spans found on the page. It shares the code with the renderer, so it should work much more reliable and you get to know where the text was and what font.]
- https://github.com/pdf-rs/pdf_tools/blob/master/src/lib.rs#L226 (untested)

**Comment by dougalg** [comment]
@s3bk thanks a lot, I will take a look at that!

**Comment by Niedzwiedzw** [comment]
@dougalg any success? I'd like to use rust for extracting text from pdfs in my project cause I'd rather not mix codebases

**Comment by dougalg** [comment]
@Niedzwiedzw I have not had a chance to test this out, it will be probably at least a few days before I can try.

**Comment by s3bk** [comment]
@dougalg I am using pdf text extraction via the pdf_render approach in a commercial product. It certainly works.

**Comment by Niedzwiedzw** [comment]
https://adventures.michaelfbryan.com/posts/parsing-pdfs-in-rust/ I was very succesful following this blog post's code

**Comment by s3bk** [comment]
Closing as it isn't the scope of the core library anymore.
