### ISSUE TITLE
Use enum variants for errors

### ISSUE THREAD

**Issue by Ploppz** [pdf-rs/pdf#4]
In the code, we often describe errors with `&'static str`, e.g. `bail!("Read past boundary of given contents.");`. I find this convenient when the code is unstable or under rewrite, as we have yet to decide on the enum variants of `ErrorKind` in `err.rs`.

At some point, we should go through the code and see what enum variants we need to have in `ErrorKind`, and use those instead of `str`, so as to accommodate for applications to do pattern matching on errors.

**Comment by s3bk** [comment]
closing with #25
