### ISSUE TITLE
Horribly slow

### ISSUE THREAD

**Issue by brmmm3** [pdf-rs/pdf#42]
Iterating over all named destination lasts for 23000 items 245s!
Doing the same with pypdf2 and using pypy lasts 8s.
For a Rust library I would expect this to be done <1s.

**Comment by s3bk** [comment]
Can you share the PDF and the code you used?

**Comment by s3bk** [comment]
I am now at 0,5s in a debug build for printing 1689 items. 65ms in release without printing them.

**Comment by brmmm3** [comment]
Unfortunately I cannot share this PDF, because it is a company internal document.
The example is interesting and the parsing time now is 1.6s for the dests with the latest git master.
But pages seems to be empty. I do not get any output.

**Comment by brmmm3** [comment]
And what I'm still missing is the feature to get the outline. What I need in the end is a list with:
PageTitle PageNumber
for the whole PDF.

**Comment by s3bk** [comment]
I implemented the Outline in https://github.com/pdf-rs/pdf/commit/aca2abcf5dd1af9e6898978e51fac4e759a5dcaa . Does that print something now?
When testing the PDF specification (`PDF3200_2008.pdf`) I get a bunch of named destinations… not quite page numbers, but something

**Comment by s3bk** [comment]
As of https://github.com/pdf-rs/pdf/commit/23aa71a2410e6cf36eab7aa785024f226ba79b01 I can extract the outline entries and page numbers from `PDF3200_2008.pdf`.
If it doesn't work for you, please ping me [on zulip](https://type.zulipchat.com/#narrow/stream/209232-pdf).

**Comment by s3bk** [comment]
I think this is solved now?

**Comment by brmmm3** [comment]
I have to check again if the performance is now acceptable.
Possible performance improvements would be:
- Preallocate several items in advance
- For getting the table of contents only a few item types are needed. So lots of items could be skipped. But for this, I think, it is better to implement some special functions.

**Comment by s3bk** [comment]
If you could profile it, I could figure out which parts are worth optimizing.

**Comment by brmmm3** [comment]
You can find profiling data here:
https://github.com/brmmm3/pdf/tree/master/examples/names/perf.data.zip
The example was run in debug mode. Hope this helps.

**Comment by s3bk** [comment]
Unfortunately that doesn't help:
 - It needs the binary and debug symbols (which I didn't think about)
 - profiling a debug build isn't particular interesting. We all know it is slow.

Can you run `cargo flamegraph` on it?
https://github.com/killercup/cargo-flamegraph

And also put this into pdf/.cargo/config
```toml
[profile.release]
debug = true
```

The generated SVG should be enough.

**Comment by brmmm3** [comment]
Here is the [flamegraph result](https://github.com/brmmm3/pdf/blob/master/examples/names/flamegraph.zip)

**Comment by s3bk** [comment]
Thanks. That is interesting…

**Comment by s3bk** [comment]
https://github.com/pdf-rs/pdf/commit/cd21f6d7fb8229344d3bad79ede82384570cf403 may have improved things a bit…

**Comment by brmmm3** [comment]
It seems to be a little bit faster. 10,3s -> 9,6s.
Here is the new [flamegraph result](https://github.com/brmmm3/pdf/blob/master/examples/names/flamegraph2.zip)

**Comment by s3bk** [comment]
From what I recall a major bottleneck are the compressed streams, which is a bit outside the scope of this library. The parser can definitely improved.

Either way, it is not horribly slow anymore.
