### ISSUE TITLE
Demo website is down

### ISSUE THREAD

**Issue by tarvos21** [pdf-rs/pdf#49]
<img width="1319" alt="截屏2020-03-1414 31 29" src="https://user-images.githubusercontent.com/18745870/76676641-9c81b200-6600-11ea-900e-27bc51617850.png">

**Comment by s3bk** [comment]
reload?

**Comment by s3bk** [comment]
There are actually a bunch of reasons it could fail… including missing WebGl2

**Comment by tarvos21** [comment]
Yeah, it works on Chrome, thanks!

On Safari, the console says:
```
panicked at 'failed to get WebGl2 context', /home/sebk/.cargo/git/checkouts/pathfinder_view-e3bb902cdb8b6e4b/7c55265/src/wasm.rs:70:47
```
