### ISSUE TITLE
Remove Adobe-own files

### ISSUE THREAD

**Issue by lrosenthol** [pdf-rs/pdf#50]
Apparently you have copied files that are proprietary of Adobe, including the aptly named AdobePiStd.otf.  However, I suspect that the entire font directory was taken from one of our installations.

Please remove these ASAP!

**Comment by s3bk** [comment]
How else do you suggest do render standard fonts?

**Comment by s3bk** [comment]
Will do, once Adobe publishes a set of standard fonts for all PDF readers to use.

**Comment by lrosenthol** [comment]
Do what ever other open source PDF solution does - use open source fonts, like those from Google or elsewhere.  Check out solutions like Poppler or PDFBox.

Also, don't forget that Adobe hasn't owned PDF since 2007 when they gave it to the world through the publication of ISO 32000-1.   And since, PDF has evolved as an open standard, recently publishing PDF 2.0 as ISO 32000-2:2017.

**Comment by lrosenthol** [comment]
Be aware that if these fonts are not removed from this repository, I will notify our (Adobe's) legal department to pursue the necessary actions...

**Comment by s3bk** [comment]
This falls under fair use, so I am not concerned about that.

It is however an issue for use in strict open-source distributions like Debian.

**Comment by leeoniya** [comment]
@s3bk you're likely risking this repo getting taken down by Github with such a response & block, since DMCA is fire-ready-aim process. might be worth leaving this issue open rather than inviting such a response?

if it is fair use, which i definitely think it is, this still has to be acknowledged by Adobe or existing use. does Debian distribute these fonts?

**Comment by s3bk** [comment]
It is removed from the repo fow now. Everyone can get them from [lbry](https://lbry.tv/pdf-standard-fonts.tar.bz:060d67b0d4f5ef9089853f3b314598e0e5d9c487) to get the viewer running.

**Comment by s3bk** [comment]
The fonts can be found in [an old release of the Adobe PDF viewer for Debian](http://ardownload.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/
AdbeRdr9.5.5-1_i386linux_enu.deb):
And AdobePiStd.ttf is [on fontpalace ](https://www.fontpalace.com/font-download/AdobePiStd/)

**Comment by leeoniya** [comment]
i don't have experience with github's DMCA process, but i'm pretty sure what they mean is "permanent" takedown.

i went through this fun process with Linode. the fact-finding and arbitration takes place after the content is forcibly removed for a minimum of 2 weeks. Adobe is clearly the copyright holder here and a font's mere existance in some random place on the web is not proof of anything. the fact that it's in an *old* release of a pdf viewer is not encouraging; is there a repo to bisect to see why it was dropped?

**Comment by s3bk** [comment]
@leeoniya The viewer is published by adobe. So everyone can get the fonts from Adobe if they want:
http://ardownload.adobe.com/pub/adobe/reader/unix/9.x/9.5.5/enu/AdbeRdr9.5.5-1_i386linux_enu.deb

**Comment by leeoniya** [comment]
publication by an entity does not confer distribution rights to the users.

you can, however, direct users to download & install the viewer from an official source to get the fonts.

you may even make available a script which downloads the official distribution onto their machine and extracts the needed fonts from it.

**Comment by s3bk** [comment]
@leeoniya freel free to write such a script.

**Comment by s3bk** [comment]
I should also point out that copyright did initially not apply to Typefaces and Adobe used a loophole and turned them into programs that genenrate the outline.
They then lobbied (bribed legislators) to add copyright to Typefaces as well.

**Comment by s3bk** [comment]
They don't have a good reputation in the Open Source community, and harassing developers certainly doesn't help with that.

**Comment by leeoniya** [comment]
i have no love for adobe, or software patents/trolling, but i also don't want to see this repo get taken down over an easily avoidable issue. there's not much point in protesting this way. the path forward is to get existing patents invalidated and lobby for copyright lengths to be shortened (we're both individually under-resourced for these tasks; i donate to the EFF)
