### ISSUE TITLE
TL operation displacing text from expected location

### ISSUE THREAD

**Issue by bellwether-softworks** [pdf-rs/pdf#74]
Via experimentation, I learned that some text that wasn't rendering in the correct location was off by a factor equal to its font size.  By adjusting [this line](https://github.com/pdf-rs/pdf/blob/860d5c0315150e59f8e885a4ce98d1cfa0211db5/render/src/lib.rs#L260) to omit the `font_size` multiplier, I am able to get the text to render as expected.

Due to the proprietary nature of the file I'm parsing, I'm unable to supply an example of this in action, and I'm unclear how to synthesize a file that demonstrates this behavior.

**Comment by s3bk** [comment]
Good catch!
leading already contains the font size.
