### ISSUE TITLE
Decoding Issues Flate

### ISSUE THREAD

**Issue by broke** [pdf-rs/pdf#80]
Hi there,
i noticed some issues while decoding BW images created with gscan2pdf.
The image is flate encoded. My guess is that unfilter with predictors isn't working properly.
Example PDF and rendered page is attached.
[bw.pdf](https://github.com/pdf-rs/pdf/files/6018572/bw.pdf)
![bw](https://user-images.githubusercontent.com/1071610/108639412-a2c91100-7494-11eb-951f-2e41caf37966.png)

**Comment by s3bk** [comment]
Hello, that does indeed look like it needs some work!

**Comment by s3bk** [comment]
Fixed in #81
