### ISSUE TITLE
UnexpectedPrimitive { expected: "Reference", found: "Dictionary" }

### ISSUE THREAD

**Issue by vbkaisetsu** [pdf-rs/pdf#86]
When I tried to open the following PDF, I got the following error:
https://arxiv.org/pdf/1801.09321.pdf
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Try { file: "/Users/k-akabe/.cargo/registry/src/github.com-1ecc6299db9ec823/pdf-0.7.2/src/file.rs", line: 277, column: 23, source: FromPrimitive { typ: "RcRef < Catalog >", field: "root", source: Try { file: "/Users/k-akabe/.cargo/registry/src/github.com-1ecc6299db9ec823/pdf-0.7.2/src/file.rs", line: 94, column: 19, source: FromPrimitive { typ: "Option < RcRef < NameDictionary > >", field: "names", source: UnexpectedPrimitive { expected: "Reference", found: "Dictionary" } } } } }', src/main.rs:4:62
```

```rust
// main.rs
use pdf::file::File as PdfFile;

fn main() {
    PdfFile::open("/Users/k-akabe/Downloads/1801.09321.pdf").unwrap();
}
```

```toml
# Cargo.toml
[dependencies]
pdf = "0.7.2"
```
This PDF can be opened without any problem in common viewers such as Firefox.

**Comment by s3bk** [comment]
Thanks. You hit a bug I feared would occur but forgot about.
Fixed in https://github.com/pdf-rs/pdf/commit/c849a901114403b78344974fd433a6962e660df7 .

I still get crashes at later pages. Working on that now.

**Comment by s3bk** [comment]
And the crash is fixed in https://github.com/pdf-rs/pdf/commit/76d8176555178b2188c68af23940ea85505b6a0d .

**Comment by s3bk** [comment]
Let me know if you need a new release to crates.io .

**Comment by vbkaisetsu** [comment]
I confirmed. Thank you very much!

**Comment by vbkaisetsu** [comment]
> Let me know if you need a new release to crates.io .

Please decide as you like. I specify the git repo until the next version is released.
