### ISSUE TITLE
Error on LineCap Integer

### ISSUE THREAD

**Issue by blackghost1987** [pdf-rs/pdf#88]
I've tried to use the "text" example with a PDF I have, but I got the following error while accessing the first page:

`Error: Try { file: "pdf\\src\\file.rs", line: 96, column: 19, source: Try { file: "pdf\\src\\object\\types.rs", line: 25, column: 36, source: FromPrimitive { typ: "Option < MaybeRef < Resources > >", field: "resources", source: FromPrimitive { typ: "HashMap < String, GraphicsStateParameters >", field: "graphics_states", source: FromPrimitive { typ: "Option < LineCap >", field: "line_cap", source: UnexpectedPrimitive { expected: "Name", found: "Integer" } } } } } }`

The "inspect_prim" tool is working fine with it, so I've used some debug logging to find the resource causing the issue, and got the following data:
![screenshot](https://user-images.githubusercontent.com/2356991/119652938-044ba380-be27-11eb-90f2-71e678ce00f5.png)

I'm a newbie regarding the PDF standard, so I can't really tell if this is a bug in the library or an issue with my PDF file. I've checked the PDF with an online validator tool though, seems like it's compilant with the PDF 1.4 standard.
Could you help me pinpoint the issue here? Why is the decoder expecting a Name? LineCap is an enum, so the Integer should work fine, right?

**Comment by s3bk** [comment]
Looks like I added the `Object` derive without checking the derive macro. Should be easy to fix ..

**Comment by blackghost1987** [comment]
Thanks for the quick fix, works fine! 👍
