### ISSUE TITLE
Error opening these PDFs

### ISSUE THREAD

**Issue by NicKoehler** [pdf-rs/pdf#97]
[pdf error.zip](https://github.com/pdf-rs/pdf/files/6900638/pdf.error.zip)

**Comment by s3bk** [comment]
@NicKoehler Thanks for the info, I will try to fix it in the next days.

**Comment by s3bk** [comment]
Seems to work as of #c8f010b .
Note that at least one file uses a non-standard BaseEncoding. I added support to parse those values, but you have to deal with it yourself.

**Comment by NicKoehler** [comment]
Luckly I just need the "/Count" for a lot of pdfs, thanks a lot, now I can read the value!
